package model.BCs.EOs;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 28 04:11:29 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cash_EOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public Cash_EOCollImpl() {
    }
}

