package model.BCs.EOs;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 26 18:51:53 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Contracts_EOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public Contracts_EOCollImpl() {
    }
}

