package model.BCs.EOs;

import com.tangosol.util.aggregator.BigDecimalAverage;

import java.math.BigDecimal;

import java.util.Date;

import model.BCs.common.Money;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 27 03:10:53 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OfficeExpences_EOImpl extends EntityImpl {
    private Contracts_EOImpl contractEntity, contractRecord;
    private Key contractPrimaryKey;
    private Date validationDate, currentDate;
    private BigDecimal expancesValue;
    private Integer expancesTypes;
    private BigDecimal contrcatOPExpances;

    /**
     * Validation method for ContractId.
     */
    public boolean validateContractId(BigDecimal contractid) {
        contractRecord = getContractRecord(contractid);
        validationDate = (Date) contractRecord.getAttribute("ContractEndDate");
        currentDate = new Date();
        if (validationDate.compareTo(currentDate) > 0)
            return true;
        return false;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ExpenceId,
        ContractId,
        ExpenceValue,
        ExpenceType,
        Contracts,
        Tasks;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXPENCEID = AttributesEnum.ExpenceId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int EXPENCEVALUE = AttributesEnum.ExpenceValue.index();
    public static final int EXPENCETYPE = AttributesEnum.ExpenceType.index();
    public static final int CONTRACTS = AttributesEnum.Contracts.index();
    public static final int TASKS = AttributesEnum.Tasks.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OfficeExpences_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.BCs.EOs.OfficeExpences_EO");
    }


    /**
     * Gets the attribute value for ExpenceId, using the alias name ExpenceId.
     * @return the value of ExpenceId
     */
    public BigDecimal getExpenceId() {
        return (BigDecimal) getAttributeInternal(EXPENCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpenceId.
     * @param value value to set the ExpenceId
     */
    public void setExpenceId(BigDecimal value) {
        setAttributeInternal(EXPENCEID, value);
    }

    /**
     * Gets the attribute value for ContractId, using the alias name ContractId.
     * @return the value of ContractId
     */
    public BigDecimal getContractId() {
        return (BigDecimal) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractId.
     * @param value value to set the ContractId
     */
    public void setContractId(BigDecimal value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for ExpenceValue, using the alias name ExpenceValue.
     * @return the value of ExpenceValue
     */
    public BigDecimal getExpenceValue() {
        return (BigDecimal) getAttributeInternal(EXPENCEVALUE);
    }


    /**
     * Sets <code>value</code> as the attribute value for ExpenceValue.
     * @param value value to set the ExpenceValue
     */
    public void setExpenceValue(BigDecimal value) {
        setAttributeInternal(EXPENCEVALUE, value);
    }

    /**
     * Gets the attribute value for ExpenceType, using the alias name ExpenceType.
     * @return the value of ExpenceType
     */
    public BigDecimal getExpenceType() {
        return (BigDecimal) getAttributeInternal(EXPENCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpenceType.
     * @param value value to set the ExpenceType
     */
    public void setExpenceType(BigDecimal value) {
        setAttributeInternal(EXPENCETYPE, value);
    }


    /**
     * @return the associated entity Contracts_EOImpl.
     */
    public Contracts_EOImpl getContracts() {
        return (Contracts_EOImpl) getAttributeInternal(CONTRACTS);
    }

    /**
     * Sets <code>value</code> as the associated entity Contracts_EOImpl.
     */
    public void setContracts(Contracts_EOImpl value) {
        setAttributeInternal(CONTRACTS, value);
    }

    /**
     * @return the associated entity Tasks_EOImpl.
     */
    public Tasks_EOImpl getTasks() {
        return (Tasks_EOImpl) getAttributeInternal(TASKS);
    }

    /**
     * Sets <code>value</code> as the associated entity Tasks_EOImpl.
     */
    public void setTasks(Tasks_EOImpl value) {
        setAttributeInternal(TASKS, value);
    }


    /**
     * @param expenceId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal expenceId) {
        return new Key(new Object[] { expenceId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
        if (operation==DML_INSERT)
            ubdateContracts();
    }

    private void ubdateContracts() {
        expancesValue = getExpenceValue();
        expancesTypes = getExpenceType().intValue();
        contractRecord = getContractRecord(getContractId());
        if (expancesTypes < 4) {
            contrcatOPExpances =
                (contractRecord.getContractExpence() == null) ? new BigDecimal("0") :
                contractRecord.getContractExpence();
            contractRecord.setContractExpence(contrcatOPExpances.add(expancesValue));
        }
    }

    private Contracts_EOImpl getContractRecord(BigDecimal contractid) {
        //         contractEntity = (Contracts_EOImpl) getContainerEntity();
//        contractEntity = this.getContracts();
        contractPrimaryKey = Contracts_EOImpl.createPrimaryKey(contractid);
        return (Contracts_EOImpl) contractEntity.getDefinitionObject().findByPrimaryKey(getDBTransaction(),
                                                                                        contractPrimaryKey);
    }

}

