package model.BCs.VOs;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.BCs.common.Money;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 25 12:08:39 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Contracts_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_CONTRACTS_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContractId,
        ContractCompanyId,
        ContractCompanyRepName,
        ContractEmpId,
        ContractDecument,
        ContractNote,
        ContractValue,
        ContractSignDate,
        ContractPrintDate,
        ContractEndDate,
        ContractType,
        ContractIncome,
        ContractExpence,
        ContractDebit,
        SignDateString,
        OfficeExpences,
        OfficeIncome,
        Tasks,
        Companies_VO1,
        Employees_VO1,
        ContactTypesStatic_VO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int CONTRACTCOMPANYID = AttributesEnum.ContractCompanyId.index();
    public static final int CONTRACTCOMPANYREPNAME = AttributesEnum.ContractCompanyRepName.index();
    public static final int CONTRACTEMPID = AttributesEnum.ContractEmpId.index();
    public static final int CONTRACTDECUMENT = AttributesEnum.ContractDecument.index();
    public static final int CONTRACTNOTE = AttributesEnum.ContractNote.index();
    public static final int CONTRACTVALUE = AttributesEnum.ContractValue.index();
    public static final int CONTRACTSIGNDATE = AttributesEnum.ContractSignDate.index();
    public static final int CONTRACTPRINTDATE = AttributesEnum.ContractPrintDate.index();
    public static final int CONTRACTENDDATE = AttributesEnum.ContractEndDate.index();
    public static final int CONTRACTTYPE = AttributesEnum.ContractType.index();
    public static final int CONTRACTINCOME = AttributesEnum.ContractIncome.index();
    public static final int CONTRACTEXPENCE = AttributesEnum.ContractExpence.index();
    public static final int CONTRACTDEBIT = AttributesEnum.ContractDebit.index();
    public static final int SIGNDATESTRING = AttributesEnum.SignDateString.index();
    public static final int OFFICEEXPENCES = AttributesEnum.OfficeExpences.index();
    public static final int OFFICEINCOME = AttributesEnum.OfficeIncome.index();
    public static final int TASKS = AttributesEnum.Tasks.index();
    public static final int COMPANIES_VO1 = AttributesEnum.Companies_VO1.index();
    public static final int EMPLOYEES_VO1 = AttributesEnum.Employees_VO1.index();
    public static final int CONTACTTYPESSTATIC_VO1 = AttributesEnum.ContactTypesStatic_VO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Contracts_VORowImpl() {
    }

    /**
     * Gets Contracts_EO entity object.
     * @return the Contracts_EO
     */
    public EntityImpl getContracts_EO() {
        return (EntityImpl) getEntity(ENTITY_CONTRACTS_EO);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public BigDecimal getContractId() {
        return (BigDecimal) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(BigDecimal value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_COMPANY_ID using the alias name ContractCompanyId.
     * @return the CONTRACT_COMPANY_ID
     */
    public BigDecimal getContractCompanyId() {
        return (BigDecimal) getAttributeInternal(CONTRACTCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_COMPANY_ID using the alias name ContractCompanyId.
     * @param value value to set the CONTRACT_COMPANY_ID
     */
    public void setContractCompanyId(BigDecimal value) {
        setAttributeInternal(CONTRACTCOMPANYID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_COMPANY_REP_NAME using the alias name ContractCompanyRepName.
     * @return the CONTRACT_COMPANY_REP_NAME
     */
    public String getContractCompanyRepName() {
        return (String) getAttributeInternal(CONTRACTCOMPANYREPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_COMPANY_REP_NAME using the alias name ContractCompanyRepName.
     * @param value value to set the CONTRACT_COMPANY_REP_NAME
     */
    public void setContractCompanyRepName(String value) {
        setAttributeInternal(CONTRACTCOMPANYREPNAME, value);
    }

    /**
     * Gets the attribute value for CONTRACT_EMP_ID using the alias name ContractEmpId.
     * @return the CONTRACT_EMP_ID
     */
    public BigDecimal getContractEmpId() {
        return (BigDecimal) getAttributeInternal(CONTRACTEMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_EMP_ID using the alias name ContractEmpId.
     * @param value value to set the CONTRACT_EMP_ID
     */
    public void setContractEmpId(BigDecimal value) {
        setAttributeInternal(CONTRACTEMPID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_DECUMENT using the alias name ContractDecument.
     * @return the CONTRACT_DECUMENT
     */
    public String getContractDecument() {
        return (String) getAttributeInternal(CONTRACTDECUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_DECUMENT using the alias name ContractDecument.
     * @param value value to set the CONTRACT_DECUMENT
     */
    public void setContractDecument(String value) {
        setAttributeInternal(CONTRACTDECUMENT, value);
    }

    /**
     * Gets the attribute value for CONTRACT_NOTE using the alias name ContractNote.
     * @return the CONTRACT_NOTE
     */
    public String getContractNote() {
        return (String) getAttributeInternal(CONTRACTNOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_NOTE using the alias name ContractNote.
     * @param value value to set the CONTRACT_NOTE
     */
    public void setContractNote(String value) {
        setAttributeInternal(CONTRACTNOTE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_VALUE using the alias name ContractValue.
     * @return the CONTRACT_VALUE
     */
    public BigDecimal getContractValue() {
        return (BigDecimal) getAttributeInternal(CONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_VALUE using the alias name ContractValue.
     * @param value value to set the CONTRACT_VALUE
     */
    public void setContractValue(BigDecimal value) {
        setAttributeInternal(CONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_SIGN_DATE using the alias name ContractSignDate.
     * @return the CONTRACT_SIGN_DATE
     */
    public Timestamp getContractSignDate() {
        return (Timestamp) getAttributeInternal(CONTRACTSIGNDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_SIGN_DATE using the alias name ContractSignDate.
     * @param value value to set the CONTRACT_SIGN_DATE
     */
    public void setContractSignDate(Timestamp value) {
        setAttributeInternal(CONTRACTSIGNDATE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_PRINT_DATE using the alias name ContractPrintDate.
     * @return the CONTRACT_PRINT_DATE
     */
    public Timestamp getContractPrintDate() {
        return (Timestamp) getAttributeInternal(CONTRACTPRINTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_PRINT_DATE using the alias name ContractPrintDate.
     * @param value value to set the CONTRACT_PRINT_DATE
     */
    public void setContractPrintDate(Timestamp value) {
        setAttributeInternal(CONTRACTPRINTDATE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_END_DATE using the alias name ContractEndDate.
     * @return the CONTRACT_END_DATE
     */
    public Timestamp getContractEndDate() {
        return (Timestamp) getAttributeInternal(CONTRACTENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_END_DATE using the alias name ContractEndDate.
     * @param value value to set the CONTRACT_END_DATE
     */
    public void setContractEndDate(Timestamp value) {
        setAttributeInternal(CONTRACTENDDATE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_TYPE using the alias name ContractType.
     * @return the CONTRACT_TYPE
     */
    public BigDecimal getContractType() {
        return (BigDecimal) getAttributeInternal(CONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_TYPE using the alias name ContractType.
     * @param value value to set the CONTRACT_TYPE
     */
    public void setContractType(BigDecimal value) {
        setAttributeInternal(CONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_INCOME using the alias name ContractIncome.
     * @return the CONTRACT_INCOME
     */
    public BigDecimal getContractIncome() {
        return (BigDecimal) getAttributeInternal(CONTRACTINCOME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_INCOME using the alias name ContractIncome.
     * @param value value to set the CONTRACT_INCOME
     */
    public void setContractIncome(BigDecimal value) {
        setAttributeInternal(CONTRACTINCOME, value);
    }

    /**
     * Gets the attribute value for CONTRACT_EXPENCE using the alias name ContractExpence.
     * @return the CONTRACT_EXPENCE
     */
    public BigDecimal getContractExpence() {
        return (BigDecimal) getAttributeInternal(CONTRACTEXPENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_EXPENCE using the alias name ContractExpence.
     * @param value value to set the CONTRACT_EXPENCE
     */
    public void setContractExpence(BigDecimal value) {
        setAttributeInternal(CONTRACTEXPENCE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_DEBIT using the alias name ContractDebit.
     * @return the CONTRACT_DEBIT
     */
    public BigDecimal getContractDebit() {
        return (BigDecimal) getAttributeInternal(CONTRACTDEBIT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_DEBIT using the alias name ContractDebit.
     * @param value value to set the CONTRACT_DEBIT
     */
    public void setContractDebit(BigDecimal value) {
        setAttributeInternal(CONTRACTDEBIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SignDateString.
     * @return the SignDateString
     */
    public Integer getSignDateString() {
        return (Integer) getAttributeInternal(SIGNDATESTRING);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OfficeExpences.
     */
    public RowIterator getOfficeExpences() {
        return (RowIterator) getAttributeInternal(OFFICEEXPENCES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OfficeIncome.
     */
    public RowIterator getOfficeIncome() {
        return (RowIterator) getAttributeInternal(OFFICEINCOME);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Tasks.
     */
    public RowIterator getTasks() {
        return (RowIterator) getAttributeInternal(TASKS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Companies_VO1.
     */
    public RowSet getCompanies_VO1() {
        return (RowSet) getAttributeInternal(COMPANIES_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employees_VO1.
     */
    public RowSet getEmployees_VO1() {
        return (RowSet) getAttributeInternal(EMPLOYEES_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContactTypesStatic_VO1.
     */
    public RowSet getContactTypesStatic_VO1() {
        return (RowSet) getAttributeInternal(CONTACTTYPESSTATIC_VO1);
    }
}

